### ISSUE TITLE
Add new mean method that uses all interations

### ISSUE THREAD

**Issue by AugustT** [BiologicalRecordsCentre/BRCindicators#11]
Add in @GPowney work on mean estimations using all iterations

**Comment by drnickisaac** [comment]
We discussed this together, There are basically two variants: 1) a geomean(occupancy) and 2) exp(mean(logit(occ))), i.e. geomean(odds). The first option is what @CharlieOuthwaite is using for her PhD "big paper analysis", the latter is what Gary is using for the 2018 pollinator indicator.

Both share a couple of features
- zero kludge: estimated occupacny of zero is reset to some small value
- requires complete time series

@GPowney to document this in the vignette. 
@CharlieOuthwaite to test option 1 against he own code.

**Comment by GPowney** [comment]
I've added a function into BRCindicators, CompositeTrends. @CharlieOuthwaite can you test this against your code, do you get the same results?!

**Comment by CharlieOuthwaite** [comment]
Just ran the "geometric_raw_occ" version on ants, the indicator values are the same.  The CIs are slightly different but I think that might be due to how things have been rescaled as mine start at 100 in year 1.

**Comment by GPowney** [comment]
These methods have been added and documented in [TrendSummaries](https://github.com/BiologicalRecordsCentre/TrendSummaries). See [here](https://github.com/BiologicalRecordsCentre/TrendSummaries/blob/master/R/CompositeTrend.R).
