### ISSUE TITLE
Noting dependency on car

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/BRCindicators#20]
The package depends on the car package being preinstalled, such that the install_github() comment throws an error if it's not installed. Can we do something to prevent this happening?

An easy solution would be to note it on the instructions, but I imagine there is a more foolproof way.

**Comment by AugustT** [comment]
I just needed to add it to the description file. Tested and works

```r
remove.packages('car')
library(devtools)
install_github('biologicalrecordscentre/brcindicators')
```
