### ISSUE TITLE
MSI jobname parameter bounces

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/BRCindicators#29]
When trying to set the jobname parameter of msi_tool via msi, msi_tool responds with an error saying that there multiple arguments for the jobname argument. I assume that the one I provide should overwrite the default one?

> msi_out <- msi(grassland.data, plotbaseyear=2010, sebaseyear=2010, index_smooth="INDEX", jobname="Grassland")

Error in msi_tool(wd = dir, inputFile = "input.csv", jobname = "MSI_job",  : 
  formal argument "jobname" matched by multiple actual arguments

**Comment by AugustT** [comment]
I have found the issue. `msi` currently passes a jobname which confuses things when a user specifies one as the user supplied one is passed via the ellipsis, resulting in the jobname argument being passed twice.

**Comment by AugustT** [comment]
If you are using the `msi` function that the jobname is not so important since the results are returned directly to R.

**Comment by AugustT** [comment]
I am pulling in a fix, seems to work for me. Can you check for yourself and close this issue if it works.

**Comment by larspett** [comment]
Works fine now, thanks!
