### ISSUE TITLE
FY is not smart

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/BRCindicators#33]
At present the `FY` part of bug_data in `bma()` uses the year numbers from the data. but the BUGS model scales everything from year 1, so `FY` must reflect this too.

**Comment by AugustT** [comment]
i.e. years should go from 1:Nyears?

**Comment by drnickisaac** [comment]
I have fixed this. I've also fixed it so that the output model is indexed by the years in the input data, as opposed to starting at 1.
