### ISSUE TITLE
plot_indicator() changes years

### ISSUE THREAD

**Issue by galinajonsson** [BiologicalRecordsCentre/BRCindicators#37]
`plot_indicator()` changes the first year to 1 as opposed to plotting the actual years.

**Comment by JackHHatfield91** [comment]
In the current format the years are specified by the user. If no year vector is provided this defaults to 1:length(indicator).

**Comment by AugustT** [comment]
Can we use the information in the bugs summary to use the proper year numbers?

**Comment by JackHHatfield91** [comment]
As far as I can tell all data is directly supplied by the user as numeric vectors

**Comment by AugustT** [comment]
The help file for `plot_indicator` shows that the **user** needs to provide the years, this is what the year argument is for
