### ISSUE TITLE
msi() plotting error

### ISSUE THREAD

**Issue by galinajonsson** [BiologicalRecordsCentre/BRCindicators#38]
I get the below plotting error when running `msi(data)`. The CV-plot is returned but not the index plot and the function doesn't run to completion.

```
Error in check.options(new, name.opt = ".X11.Options", envir = .X11env) : 
  c("invalid argument name ‘restoreConsole’ in 'jpeg(filename = jobnameGRAPH, width = 480, height = 480, units = \"px\", '", "invalid argument name ‘restoreConsole’ in '    pointsize = 12, bg = \"white\", res = NA, restoreConsole = TRUE)'")
```

`msi_out <- msi(data, plot = FALSE )` runs without any issues so I suspect there's an issue with the index plot.

**Comment by AugustT** [comment]
I now also get this error when working on a linux machine
