### ISSUE TITLE
Documentation for Lambda Indicator array

### ISSUE THREAD

**Issue by galinajonsson** [BiologicalRecordsCentre/BRCindicators#39]
The documentation for the array structure needed to run `lambda_indicator()` could do with some clarification. I assume the `data` in the below example should be the occupancy/index values from first to last year of sp1 followed by first to last year of sp2 etc. but it's not entirely clear from the documentation. 

```
# Build a random set of data
myArray <- array(data = rnorm(n = nsp*nyr*iter,
                               mean = 0.5,
                               sd = 0.1),
                  dim = c(nsp, nyr, iter),
                  dimnames = list(paste0('SP',1:nsp),
                                  1:nyr,
                                  1:iter))
```

**Comment by JackHHatfield91** [comment]
Yes, the example that you give produces an array in the correct format. I will look at adding more information to the function help.

**Comment by AugustT** [comment]
Yeah, a text description would be nice

**Comment by JackHHatfield91** [comment]
Should now be covered in recent pull request
