### ISSUE TITLE
rescaleYr in bma()

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/BRCindicators#4]
I have modified the code in bma()
Previously, there was an argument rescaleYr1 with a default value of TRUE
I've replaced this with an argument rescaleYr with a default value of 1.
In the new version, it allows the indicator to be set to zero at some year other than 1.

Existing code *should* be compatible with this change unless rescaleYr1  was set to FALSE. It can be made compatible by replacing  rescaleYr1  with rescaleYr in the function call.
(any other formulation would have used the same default (1 = TRUE) and report that rescaleYr1 is an unused parameter.

However, I'd appreciate @AugustT checking for unintended consequences.

**Comment by AugustT** [comment]
I'll have a think

**Comment by DylanCarbone** [comment]
The rescaleYr parameter has been added to the function documentation. I'm closing this issue
