### ISSUE TITLE
Check Jack's changes in sparta's downstream affects

### ISSUE THREAD

**Issue by AugustT** [BiologicalRecordsCentre/BRCindicators#40]
ie `min_year`

**Comment by JackHHatfield91** [comment]
I checked and this should be fine. My changes in SPARTA were made to the metadata in the attribute data. These functions use the value listed in the out object which I left alone for compatibility.

**Comment by AugustT** [comment]
2 issues down without a line of code written... your on fire!

**Comment by DavidRoy** [comment]
surely it should be _you're_ on fire.

pedantically yours....

**Comment by AugustT** [comment]
Don't make me report you for abuse...

![Untitled](https://user-images.githubusercontent.com/3987564/66828073-0f9ad580-ef48-11e9-80fd-f43d2e7c2159.png)
