### ISSUE TITLE
Add a function to standardise data to a common value

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/BRCindicators#45]
to be called at line 103 of `bayesian_meta_analysis`
Make it optional
`rescale_species` already does this - utilise?

**Comment by drnickisaac** [comment]
I tried to write a bit of code today that would do this job. It's complicated because rescale_species uses a multiplier to scale the data. Steve Freeman prefers to start each time-series at zero, which requires a substraction.

**Comment by drnickisaac** [comment]
I have now implemented this (locally). I've added an optional argument rescale_indices that defaults to NULL.  It takes an integer determining the starting value for each species.

**Comment by AugustT** [comment]
Please only close once it is accepted into the repository
