### ISSUE TITLE
Installing BRC Indicators requires JAGS to be pre-installed

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BRCindicators#53]
Required:
https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.0.exe/download

before this works:
library(devtools)
install_github(repo = 'biologicalrecordscentre/BRCindicators')

**Comment by AugustT** [comment]
The requirement is on `rjags` which in turn requires JAGS (needed `bma`). The solution is to move rjags to suggests and then have something responsive to the value of `require(rjags)` that walks users through what they need to do. Some users will never use JAGS so we shouldn't have the requirement to install it.

**Comment by AugustT** [comment]
requirement is actually on `jagUI` a wrapper around rjags
