### ISSUE TITLE
BMA  default option doesn't work

### ISSUE THREAD

**Issue by AugustT** [BiologicalRecordsCentre/BRCindicators#58]
https://github.com/BiologicalRecordsCentre/BRCindicators/blob/abae2ddde01ece2b7e42861f8eca8c7babb347f0/R/bayesian_meta_analysis.R#L60

Quick fix needed @drnickisaac 

It appears the default does not work. There is no model option for 'smooth'; compare the model default ('smooth'), to the list of options from L91

I know I sound like a broken record but this is why it is really important to have tests. I don't think I will be excepting any new pull requests on any BRC projects unless they provide tests for the new features they add.

**Comment by drnickisaac** [comment]
Done on my version - now with pull request.

**Comment by AugustT** [comment]
Best not to close it in case there are issues with the pull request. Instead you can now link this issue to your pull request on the right hand side of this page, when the pull request is merged this issue automatically closes. I have just done that for this issue.
