### ISSUE TITLE
Meet to review modular design

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/BRCindicators#6]
We should revisit the architecture and scope of the package.

**Comment by drnickisaac** [comment]
The package will run several options for indicator calculation:
1. BMA (several variants)
2. bootstrap across sites
3. MSI
4. LPI
.... others?

We want to get to a place where all methods have functions that accept data in the same format, and that feed into functions for rescaling and plotting.

**Comment by AugustT** [comment]
@drnickisaac @CharlieOuthwaite @GPowney Talk about models we have and to include
