### ISSUE TITLE
rescale_Yr doesn't behave as expected

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/BRCindicators#67]
@galinajonsson noticed unexpected behaviour. `rescaleYr` treats the uncertainty as expected but does not scale the overall indicator to the baseline value in this year. Should be easy to fix.

**Comment by AugustT** [comment]
is this internal to the bma function?

**Comment by drnickisaac** [comment]
Yes, `rescaleYr` is an argument to `bma()`. This is what I will explore and fix.
But it's possible there are rescaling options elsewhere in the package.

**Comment by drnickisaac** [comment]
I have explored the behaviour of `rescaleYr` in `bma()` and it behaves as I expected, at least when `errorY1 = FALSE`. When `errorY1 = TRUE` the only noticeable effect is to shift the line up or down. So I imagine that @galinajonsson used a different function for rescaling. 
I'll close this issue now: there remains a question about which options we make available, and how they are explained/expressed. But that's more general than this issue, and probably falls under wider issues around harmonization and documentation.
