### ISSUE TITLE
obtain some reference datasets

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/BRCindicators#8]
Within the package, we should have a set of datasets for testing and comparing the performance of the functions.

**Comment by AugustT** [comment]
The output of msi can still co into our plot function

**Comment by drnickisaac** [comment]
The datasets going into Freeman et al paper would be ideal candidates: UK bats, UK butterflies and Dragonflies (from Charlie's data).

**Comment by AugustT** [comment]
This should be straight forward as long as you have the data sets in a ready to use format. Also can you confirm that we have permission to make these data sets openly available in this way? @drnickisaac

**Comment by AugustT** [comment]
Nick has shared these data sets with me. I need to document them and put them in the package
